Allow cors for replays
FAForever/faf-stack pull request #174
Opened 2021-05-13 20:19 UTC by norraxx

https://doc.traefik.io/traefik/middlewares/headers/#cors-headers

2021-05-13 20:20 UTC, norraxx commented
`docker-compose up -d faf-content`
tested on test, it's working

2021-05-14 00:21 UTC, p4block requested changes
If this is what you need, just rename "testheader" to something more descriptive and it looks good to me. 

I'm unsure if specifying the false vary header is needed, or if 60 is a good amount for maxAge, but this is definitely valid Traefik syntax :smile:

2021-05-14 02:57 UTC, norraxx commented
I see, testheader can be renamed? :-) donno how traefik works with that long variables. I'll change this stuff

2021-05-16 12:40 UTC, p4block approved these changes

2021-05-18 21:43 UTC, merged