Add new php-based UnitDB  (fixes #16)
FAForever/faf-stack pull request #27
Opened 2018-02-15 22:54 UTC by Brutus5000

- [ ] tested on test server

2018-04-14 09:43 UTC, micheljung requested changes

2018-04-14 09:43 UTC, micheljung commented on .env.template
> +FAF_FS_PGID=1000
These are UIDs on the host system, faf-stack should not make any assumptions.
Keep them `root`

2018-04-14 09:43 UTC, micheljung commented on config.template/faf-unitdb/datafiles.json
> +]
Seeing that there are version numbers in the files, will this work out of the box when I clone faf-stack, and copy this config over? Or will the application throw a file not found error at me, cause me time to investigate the issue only to find out that the default is misconfigured?

If so, I suggest commenting-out this (at least the content of the array) so it's clear that it's just for reference. Not sure how the application behaves when we do.

2018-04-14 09:43 UTC, micheljung commented on config.template/faf-unitdb/locfiles.json
> +	"DATA/LOC/loc.nmd"
Same

2018-04-14 18:53 UTC, micheljung approved these changes

2018-04-14 18:53 UTC, merged

2018-04-16 11:20 UTC, Brutus5000 commented on config.template/faf-unitdb/datafiles.json
> +]
No this is the biggest problem with this particular unitdb.
It requires version-specific files and they also need to be in the order of the patches.

If you don't provide any the unitdb won't work.
The 3599-files should be the retail files afaik.