Closes #55 Switch to newer spring boot admin server compatible with sb2
FAForever/faf-stack pull request #58
Opened 2018-11-04 14:46 UTC by bukajsytlos

Closes #55 Switch to newer spring boot admin server compatible with sb2

2018-11-06 11:09 UTC, micheljung approved these changes

2018-11-06 11:10 UTC, micheljung requested changes

2018-11-06 11:10 UTC, micheljung commented on docker-compose.yml
> +        - "3306:3306"
Don't remove this; it makes our database publicly accessible

2018-11-12 22:21 UTC, Brutus5000 approved these changes

2018-11-12 22:21 UTC, merged