Use localhost as default values
FAForever/faf-stack pull request #7
Opened 2017-05-29 15:42 UTC by IDragonfire

2017-05-30 09:00 UTC, micheljung requested changes
I know you know how docker works, and I know that you can make it work if you just take the time, think and test instead of just throwing something together rather unthoughtful.

Instead it cost me **another** 15min to review and explain 3 lines of configuration.

2017-05-30 09:00 UTC, micheljung commented on config.template/faf-clans/faf-clans.env
> +OAUTH_CLIENT_ID=11111111-2222-3333-4444-555555555555
Is that what other apps specify?
https://github.com/FAForever/faf-stack/blob/develop/config.template/faf-website/faf-website.env#L8

2017-05-30 09:00 UTC, micheljung commented on config.template/faf-clans/faf-clans.env
> +OAUTH_REDIRECT_URI=https://localhost
Does that work?
This makes you being redirected to `http://localhost:`. And there you get a connection refused. Is that what you want?
So it should probably be `http://localhost:8096`

2017-05-30 09:00 UTC, micheljung commented on config.template/faf-clans/faf-clans.env
> +API_BASE_URL=https://localhost:8010
Does that work?

The clanapp-container can't access `https://localhost:8010`. It needs to be `https://faf-java-api:8010`
Just like another app does it... https://github.com/FAForever/faf-stack/blob/develop/config.template/faf-website/faf-website.env#L7

2017-07-19 13:13 UTC, micheljung requested changes

2017-07-19 13:13 UTC, micheljung commented on config.template/faf-clans/faf-clans.env
> +API_BASE_URL=https://faf-java-api:8010
Container-to-container connections aren't HTTPs; this will not work.

2017-07-19 13:13 UTC, micheljung commented on config.template/faf-clans/faf-clans.env
> +OAUTH_REDIRECT_URI=https://localhost:8096
This HTTPs won't work either

2017-07-19 21:06 UTC, IDragonfire commented on config.template/faf-clans/faf-clans.env
> +API_BASE_URL=https://faf-java-api:8010
This is not the container connection ...
This is the hosted address of the api ...

2017-07-19 21:07 UTC, IDragonfire commented on config.template/faf-clans/faf-clans.env
> +OAUTH_REDIRECT_URI=https://localhost:8096
This is the hosted address of the app for the redirect ...

2017-07-20 07:03 UTC, micheljung commented on config.template/faf-clans/faf-clans.env
> +API_BASE_URL=https://faf-java-api:8010
If it's the browser that connects to this URL, then it has to be `http://localhost`

2017-07-20 07:04 UTC, micheljung commented on config.template/faf-clans/faf-clans.env
> +OAUTH_REDIRECT_URI=https://localhost:8096
Doesn't change the fact that we have no HTTPs locally

2018-10-27 09:46 UTC, Brutus5000 commented
Closed due to inactivity

2018-10-27 09:46 UTC, closed without merging