Update grafana and prometheus to latest versions
FAForever/faf-stack pull request #92
Opened 2019-07-12 22:47 UTC by Askaholic

On the test server, prometheus was able to update and start without issue. Grafana tries to create files, but because `data/faf-grafana` is owned by FAForever it cannot create any new files. Db migrations or actions that only need to modify the existing files seem to complete correctly.

2019-07-17 20:42 UTC, Brutus5000 reviewed
**Migration notice**
Grafana needs a migration after upgrade:
https://grafana.com/docs/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later

Prometheus will lose all its data due to incompatible changes, so we need to cleanup the data folder:
https://prometheus.io/docs/prometheus/latest/migration/

2019-07-17 20:44 UTC, Brutus5000 requested changes
Prometheus lost all data on prod 4 weeks ago on the last recreate of the containers (I updated the Docker engine). We should configure Prometheus properly so we keep the data.
Some of the mounts need to be fixed I guess.

2019-07-19 22:30 UTC, Brutus5000 commented
Looks like default data retention is just 15 days for prometheus.

2019-07-19 22:45 UTC, Askaholic commented
Aaah. That makes sense. How big is the `data` folder for that amount of time? How high can we afford to set that?

2019-07-20 22:02 UTC, Brutus5000 commented
I think we can afford 2 years.

2019-07-28 13:39 UTC, Brutus5000 approved these changes

2019-07-28 13:39 UTC, merged